ptf, src/ptf/base_tests.py, src/ptf/testutils.py
This pull request adds the following features:
- failfast mode (enable with --failfast): test execution stops as soon as one test fails
- before_send and at_receive 'hooks': stub methods added to BaseTest class, called when a packet is sent (resp. received), can be overloaded by children classes when needed
- ability to specify execution order for tests using --test-order: choices are 'default' (command line order), 'lexico' (string ordering on test names), 'rand' (random, seed can be specified using --test-order-seed)
=> Misc improvements

src/ptf/testutils.py
Clarified that verification failed to receive 'expected' packets.
=> clarified verification error messages

src/ptf/afpacket.py
Otherwise your exception will like this one
RuntimeError: ('recvmsg failed: rv=%d', -1)
=> Use right operation for creating exception string

ptf_nn/ptf_nn_agent.py, src/ptf/dataplane.py
This pull request gives the PTF NN agent the ability to wait for an interface to become available before receiving packets. The agent will also bring an interface up / down based on `MSG_PORT_STATUS_UP` / `MSG_PORT_STATUS_DOWN` messages.
=> Set if status for nn dataplane

src/ptf/dataplane.py
There might be racy access to pcap_writer from stop_pcap(self)
while receiving packets by DataPlane thread.
The issue might be reproduced with simple send-only scenario:
class Dummy(some_base_test):
def runTest(self):
pkt = simple_tcp_packet(eth_dst='00:22:22:22:22:22',
eth_src='00:11:11:11:11:11',
ip_dst='10.0.0.1',
ip_id=101,
ip_ttl=64)
for i in range(0, 1000):
send_packet(self, 0, str(pkt))
Fixed by locking cvar in stop_pcap(self) before close pcap_writer.
Signed-off-by: Vadim Kochan <vadymk@mellanox.com>
=> dataplane: Fix race access in stop_pcap(self)

src/ptf/testutils.py
Extend ip & ipv6 related packet creation functions with ecn & dscp
parameters, the reason for this is to simplify setting of these ToS/TC
fields w/o additional bitwise operations.
Added simple ip_make_tos(tos, ecn, dscp) helper which overwrites ip_tos/ipv6_tc
considering ecn & dscp values in every ip/ipv6 simple_xxx_packet function.
Signed-off-by: Vadim Kochan <vadymk@mellanox.com>
=> testutils: Add ecn & dscp params to simple_xxx_packet funcs

src/ptf/testutils.py
Add optional 'count' parameter to send & send_packet functions to send
a 'count' times same packet.
The reason is just to simplify the following use case:
for n in range(pkts_count):
send_packet(self, port_id, pkt)
to:
send_packet(self, port_id, pkt, count=pkts_count)
Signed-off-by: Vadim Kochan <vadymk@mellanox.com>
=> testutils: Extend send/send_packet to specify a number of packets

ptf_nn/ptf_nn_agent.py
Sometimes an interface is presented in /sys/class/net hierarchy, but OS returns an error when we check a status of the interface.  When we have such error it means the interface is not ready yet, so we return False from get_if_status() function
=> Catch exceptions when checkint interface status

src/ptf/testutils.py
The testutils.py looks at sgt_other field to add platform subheader but
it should mask it and only check the last bit not the whole.
=> Fixes erspanIII platform subheader creation bug

ptf, src/ptf/dataplane.py
Done with command-line option '--socket-recv-size', default is 4096.
=> Add ability to set the socket.recv buf size

example/mytests/switch.py, src/ptf/dataplane.py, src/ptf/testutils.py
Debugging PTF test failures can currently be quite painful, because the messages printed when tests fail aren't very informative. It would be better to print much more information in the case of a test failure, and to print this information all the time (rather than merely when debug logging is on) so that it is reported on CI infrastructure.
This PR adds code to display information about the packets we expected and the packets we actually received when tests fail, in the spirit of @jklr's PR #27.
One concern about the patch in #27 was that it reported this information in the `DataPlane` polling code, which isn't a good fit since we have a variety of `verify*()` functions with very different expectations. For example, `verify_packet_any_port()` can poll on many ports, and the test passes …
=> Improve test failure messages

ptf_nn/ptf_nn_agent.py
Otherwise ptf_nn_agent could crash if Nanomsg socket receives a packet to send, but an Interface which will be used to send the packet is still not ready to send it
=> [ptf_nn_agent]: Don't start Nanomsg sockets until all Ifaces are up

.travis.yml, ptf_nn/ptf_nn_test/test.py, src/ptf/testutils.py
There was a bug: if one of the expected packets was received on an
unexpected port, the function would not raise an error.
=> Fix verify_any_packet_any_port implementation

src/ptf/dataplane.py
Checks that the port exists for a device and prints an error message
rather than reporting key error on self.ports.
Prints a warning message when sending less than 15 bytes (on Linux),
as the Linux kernel does not send small packets. This helps debugging.
=> improves warning and error messages

.travis.yml
Travis regressions started failing (cannot import nnpy). Not sure why removing `language: generic` fixes the issue, but it does. If I run into more issues, will run this inside a docker image.
=> Fixing travis regressions

setup.py, src/ptf/mask.py, src/ptf/packet.py
pkt_match was strictly comparing the length of the packet argument with the size of the mask. It is desirable to compare only the prefix given by the mask.size. Also fixed the printing of masks to match how we print packet output using hexdump -- it captures the print output in a buffer that is then returned.
Replace the direct check of `not config['key']` with `not config.has_key('key')` to avoid throwing an exception when importing packet directly.
And finally, bump the version to 0.9.1
=> fix mask packet comparison

src/ptf/dataplane.py
Someone higher in the call stack (in our case the unit test xmlrunner)
may have already overwritten sys.stdout, in which case we would not be
restoring sys.stdout to the correct value.
=> Do not use sys.__stdout__ to restore sys.stdout

src/ptf/dataplane.py, src/ptf/mask.py
This only affects hex dumps for masked packets. Before this fix, it printed:
========== EXPECTED ==========
Mask: 0000   00 11 22 33 44 55 00 0A  0B 0C 0D 0E 08 00 45 00   .."3DU........E.
0010   00 20 00 01 00 00 40 11  F9 78 C0 A8 00 01 C0 A8   . ....@..x......
0020   00 02 04 D2 10 E1 00 0C  00 00 00 00 01 00         ..............
With this fix there's a newline after `Mask:`:
========== EXPECTED ==========
Mask:
0000   00 11 22 33 44 55 00 0A  0B 0C 0D 0E 08 00 45 00   .."3DU........E.
0010   00 20 00 01 00 00 40 11  F9 78 C0 A8 00 01 C0 A8   . ....@..x......
0020   00 02 04 D2 10 E1 00 0C  00 00 00 00 01 00         ..............
=>  Print aligned hex dump in assertion

src/ptf/packet.py
ARP class was moved from `scapy.layers.inet.ARP` to `scapy.layers.l2.ARP`. Tested with scapy v2.4.2.
=> Fix ARP import error when using more recent versions of scapy

src/ptf/testutils.py
New API simple_tcp_packet_ext_taglist to create tcp packet with a tag list.
Let simple_tcp_packet invoke simple_tcp_packet_ext_taglist.
New API simple_eth_raw_packet_with_taglist to create eth packet with a tag list.
=> [TestUtils]:Support creat eth and tcp packets with a tag list

.travis.yml, CI/travis/install-nnpy.sh, ptf, src/ptf/__init__.py, src/ptf/packet.py, src/ptf/platforms/dummy.py, src/ptf/testutils.py, utests/specs/test.py, utests/tests/test.py
Log an error message when the string passed to --test-params cannot be
evaluate by Python's exec method.
Also includes some minor improvement to logging. In particular, some scapy
error logs are suppressed and we now log errors to stdout.
We test the new --test-params code with some Python (python3) unit
tests. Unfortunately ptf is not very unit test friendly at the moment so we
actually start a ptf process with subprocess and inspect stdout /
stderr. Ideally, the ptf script would be change in the future so that ptf can be
run as a function and methods can be independently tested.
=> Better --test-params handling

src/ptf/testutils.py
This is an encapsulated IPv4 packet, not IPv6: https://github.com/p4lang/ptf/commit/23bd407730f3fced8ebb1f141c4b503b8162148c#diff-e724841c5944b5f3968e59b558a34cd3R1393
=> Fix IP protocol number for encapsulated IPv4

setup.py
We would like to have ptf_nn_agent script as part of ptf package.
Currently we install ptf as deb package, and end up using `wget`  to get the `ptf_nn_agent.py`.
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
=> [setup] include ptf_nn_agent script in the package

src/ptf/testutils.py
When call **_[simple_eth_raw_packet_with_taglist()](https://github.com/p4lang/ptf/blob/c916077de445d6f604048580ed8b7af8e2d0daa7/src/ptf/testutils.py#L1703)_** with with **_False_** as  **[_dl_taglist_enable_](https://github.com/p4lang/ptf/blob/c916077de445d6f604048580ed8b7af8e2d0daa7/src/ptf/testutils.py#L1706)** paramters, we can see next error:
`IndexError('Layer [Dot1Q] not found',)`
=> Fix crash in simple_eth_raw_packet_with_taglist()

ptf_nn/ptf_nn_agent.py
afpacket.recv will throw RuntimeError when sniffed interface had link flipped. (when raw socket failed)
IfaceMgr doesn't catch the RuntimeError causing thread exit the main loop, thus can't receive packet anymore.
=> Fix uncatched RuntimeError throwed when socket error while receiving packet

README.md, setup.py
Comparability with Python 3 has already been introduced with https://github.com/p4lang/ptf/pull/106.
Resolves #132
=> Document Python 3 support

ptf
Hi all, I'll provide some context to this PR below:
I am using the PTF framework as part of designing a new suite of tests to assess the performance of a P4 implementation on a leaf-spine fabric.
The existing test suite utilized profiles, which thus specified which test groups to perform. For example, if the `int` profile was specified, PTF tests for groups "all ^spgw ^bng ^dth ^p4rt ^int-dod" would be performed. 
For this new suite of tests, we are not using *all* of these groups anymore, but we are still using the profile approach (i.e. `int`) for readability, continuity, and practicality. The profile specification approach goes through the same Makefile regardless of test suite, which means that the PTF call for both the new and previous suite will still specify the groups "all ^spgw …
=> Change prune_tests to only fail if a non-negated group is not matched

src/ptf/testutils.py
This PR fix the following error:
```
TypeError: format_failure() takes exactly 2 arguments (1 given)
```
=> fix(testutils.py): fix syntax error

.github/workflows/build.yml, README.md, src/ptf/packet.py, src/ptf/testutils.py
Scapy 2.4.4 supports `VXLAN`, `ERSPAN`, `GENEVE`, `MPLS`
We can include them from the Scapy directly without installing the `p4lang/scapy-vxlan`
Also some cleanup to the test utility
- Missing `scapy.` for some types (e.g., Dot1Q should be scapy.Dot1Q)
- Use `int` instead of `long` since they already unified, see [EP237](https://www.python.org/dev/peps/pep-0237/)
=> Some cleanup to packet library and the testutils

src/ptf/testutils.py
The default Scapy implementation assumes VXLAN GPE and sets the vxlan flags to 0xC for Ethernet header. Allowing flags to be defaulted to 0x8 allows it to function as basic Vxlan. This was the original behavior with scapy-vxlan.
=> allow app to pass vxlan flags to simple_vxlan_packet

ptf, src/ptf/platforms/eth.py, src/ptf/testutils.py
Еhe possibility of passing port parameters for each specific interface provided: 
`--interfaces=0-1@veth1;speed=100g-r2;fec=rs;mtu=9192;other_param=some_value `
**Example:** 
```
{ 
            "device_port":64, 
            "if":"ens1f0", 
            "speed":"25G", 
            "conn_id":65, 
            "chnl_id":0 
} 
```
**Command:** 
`--interfaces=0-64@ens1f0;64;chnl_id=0;device_port=64;speed=25G;conn_id=65;if=ens1f0 `
To access the port parameters inside a test the `port_param_get()` API provided: 
`ptf.testutils.port_param_get(port, 'speed') `
=> Provide ptf support for passing port information with --interface option

src/ptf/testutils.py
1. `seqence_number` -> `sequence_number` (typo) per https://github.com/secdev/scapy/blob/95ba5b8504152a1f820bbe679ccf03668cb5118f/scapy/layers/l2.py#L467
2. `scapy.ERSPAN` parameters update per https://github.com/secdev/scapy/blob/95ba5b8504152a1f820bbe679ccf03668cb5118f/scapy/contrib/erspan.py#L45
=> ERSPAN and GRE fixes for Scapy

ptf
Sometimes we are seeing error logs missing and just "script exist (1)" text. This change is made in order to force buffer flush.
=> Adding stdout flush before exit(1)

Makefile, ptf
Add a `ptf` file for the Black watch.
Excluded still will be `example`, `ptf_nn` & `utests` (additional work with the files to be cross-compatible with Py3, need to be done).
=> Add `ptf` file to Black

README.md, ptf
From now, it is possible to achieve parallelization by splitting tests into N groups and running them with separate PTF processes.
Each PTF instance will run disjoint subset of all selected tests.
=> Add support for sharding

Makefile, src/ptf/testutils.py, utests/tests/ptf/test_testutils.py
Closes https://github.com/p4lang/ptf/issues/157
=> Correct setting mrtime/mrcode for IGMP

src/ptf/testutils.py
At this moment, functions `ipv4_erspan_pkt` and `ipv4_erspan_platform_pkt` in testutils do not expose flag fields of ERSPAN_III: `p`, `ft`, `hw`, `d`, `gra` and `o`.
This PR adds to these functions arguments for these flags, keeping backward compatibility with `sgt_other` field.
=> Expose ERSPAN_III flags in testutils functions

setup.py, src/ptf/mask.py, utests/tests/ptf/test_mask.py
Closes: #162
Some Scapy'ies Packets contain  `Conditional Fields`, like `VXLAN`. 
The previous mechanism tries to find elements to mask, using a `field_desc` which represents the entire raw packet with all options, not a specific version of the packet.
All the fields that were taken by the mechanism:
```text
["flags <class 'scapy.fields.FlagsField'>", 
"reserved0 <class 'scapy.fields.ConditionalField'>", 
"NextProtocol <class 'scapy.fields.ConditionalField'>", 
"reserved1 <class 'scapy.fields.ConditionalField'>", 
"gpflags <class 'scapy.fields.ConditionalField'>", 
"gpid <class 'scapy.fields.ConditionalField'>", 
"vni <class 'scapy.fields.X3BytesField'>", 
"reserved2 <class 'scapy.fields.XByteField'>"]
```
when we provide such example:
```
VXLAN(flags=0x80, gpflags=0x23, gpid=0x1234, …
```
=> Potential fix for scapy'ies conditional field mask (for #162)

ptf
Default behavior of `--test-order` option is described as:
> tests are run in the order in which they appear on command line
In case `test_specs` contains only group names, the order of tests within the single group is not defined and may depend on filesystem implementation. 
To avoid this issue files/directories should be visited in a stable order.
=> Guarantee that tests are loaded in stable order

src/ptf/testutils.py
There is an issue with VxLAN API when you try to send VxLAN packet and compare with expected VxLAN pkt received on another port for example. verify_packet returns assert, even if you send VxLAN packet and expect the same VxLAN packet (with the same fields).
The problem is that vxlan_reserved0 value of sent packet and received packets is different (0 vs None). So, to fix this, make sure this filed is zero.
Signed-off-by: Oleh Yakymenko <olehx.yakymenko@intel.com>
Signed-off-by: Volodymyr Mytnyk <volodymyrx.mytnyk@intel.com>
=> ptf: testutils: add parameter vxlan_reserved0 to simple_vxlan_packet

src/ptf/dataplane.py
When there are separate threads that are sending and receiving packets, both threads may try to write the packet data to the pcap file. This causes the packet to get interleaved, thus basically making it corrupted and unable to be read by tcpdump, wireshark, etc.
This is happening due to a missing lock on `self.cvar`. Fix it by wrapping the write call in the `send` method and the initial assignment in `start_pcap` method with a lock on `self.cvar`.
=> Fix a multithreading issue in writing pcap files

.github/workflows/build.yml
Without this, I have seen many failures recently on Ubuntu 22.04 that I do not know the root cause of, but using a venv gives consistently passing results.
=> Use Python venv in CI tests
