src/ptf/testutils.py
Fix to transmit large packets.
=> Fix for transmitting large packets

src/ptf/testutils.py
1. Take sgt_other ERSPAN_III field value in ipv4_erspan_pkt().
2. Print capital letters in hex_dump_buffer()
=> changes to testutils.py

src/ptf/dataplane.py
=> fixed ifconfig usage for dp down() and up() methods

src/ptf/dataplane.py
=> import struct and defaultdict in dataplane.py

src/ptf/testutils.py
This function receives all packets on the port, counts how many packets where expected, and returns this counter
=> Add count_matched_packets function

src/ptf/packet.py, src/ptf/testutils.py
Hi there,
Added four way DHCP packet functions. DHCP discover and request are very similar as are offer and ack. I kept them split up for readability and future expansion. Further DHCP option support can be added to each of these functions. Let me know what you think.
=> added dhcp discover, offer, request, ack (four way handshake)

ptf_nn/ptf_nn_agent.py, src/ptf/dataplane.py
Frequently we need to check how many packets were sent/received through physical interfaces.
So I introduce counters for NN dataplane
=> Introduce get_counters method to dataplane class

src/ptf/testutils.py
Added DHCP release function. Releases client address.
=> added dhcp release function

ptf_nn/ptf_nn_agent.py
Add --verbose flag to enable it back
=> Mask excessive output about packet received packets.

ptf_nn/ptf_nn_agent.py
Add options to increase RCV and SND buffer sizes to avoid dropping transit packets.
=> ptf_nn_agent: Add command line options to specify buffer sizes for ifaces and nn sockets

src/ptf/testutils.py
Adding id field for simple udp packet and then adding udp checksum and payload parameters for simple udp v6 packet.
=> Mpls udp changes

src/ptf/afpacket.py
Currently only ETH_P_8021Q was used. But correct tpid is provided by the kernel as part as auxdata. Use this information to reinsert correct tpid
=> Reinsert correct vlan_tpid in afpacket

ptf, src/ptf/packet.py, src/ptf/testutils.py
=> Add IGMP support for PTF

src/ptf/testutils.py
Add ICMPv6 muticast support for PTF
=> Add ICMPv6 muticast support for PTF

ptf_nn/ptf_nn_agent.py
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
Fixes #107
=> [ptf_nn_agent] enable capturing vlan tag by using afpacket

src/ptf/testutils.py
Fixing break of https://github.com/p4lang/ptf/pull/127
=> Fixing backward compatibility break of verify_any_packet_any_port

.gitignore, README.md, setup.py
- Fix setup.py
- Add new installation instruction
Fixes #148
=> Support pypi.org

src/ptf/dataplane.py
Update DataPlanePortNN to allow for multiple DataPlanePacketSourceNN on the same device.  This allows PTF to use multiple nanomsg sockets to implement the ports on a single device.
=> Allow PTF to use multiple nanomsg sockets

.github/workflows/build.yml, CI/travis/check-nnpy.py, CI/travis/install-nnpy.sh
The workflow was stale (in particular ubuntu-18.04 hosted runners are no longer available).
=> Update Github workflow

.github/workflows/build.yml, .gitignore, ptf, pyproject.toml, src/ptf/__init__.py
Use setuptools to write a src/ptf/_version.py file.
Fixes #186
=> Fix ptf --version

README.md, requirements-dev.txt, setup.cfg
Also remove last mention of 'six' package that was removed recently.
=> Remove empty requirements.txt to avoid install issues on some platforms
